# Generated by Django 4.0.6 on 2022-08-05 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0004_alter_empleado_salario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('sexo', models.CharField(blank=True, choices=[('F', 'Femenino'), ('M', 'Masculino'), ('O', 'Otro')], max_length=1)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('dni', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('direccion', models.CharField(max_length=80)),
                ('telefono', models.IntegerField(blank=True)),
                ('numero_seguridad', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
