# Generated by Django 4.0.6 on 2022-08-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_seguridad_nombre_seguridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguridad',
            name='nombre_seguridad',
            field=models.CharField(max_length=8),
        ),
    ]
