# Generated by Django 4.0.6 on 2022-08-05 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0007_alter_seguridad_nombre_seguridad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seguridad',
        ),
    ]
