# Generated by Django 4.1 on 2022-08-12 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0008_delete_seguridad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='Foto',
            field=models.ImageField(null=True, upload_to='Productos/'),
        ),
    ]
