# Generated by Django 4.1 on 2022-08-12 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0009_alter_productos_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='Foto',
            field=models.ImageField(blank=True, null=True, upload_to='Productos/'),
        ),
    ]
